// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BButton: typeof import('bootstrap-vue')['BButton']
    BCard: typeof import('bootstrap-vue')['BCard']
    BCol: typeof import('bootstrap-vue')['BCol']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BFormFile: typeof import('bootstrap-vue')['BFormFile']
    BInputGroup: typeof import('bootstrap-vue')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue')['BInputGroupAppend']
    BListGroup: typeof import('bootstrap-vue')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue')['BListGroupItem']
    BOverlay: typeof import('bootstrap-vue')['BOverlay']
    BRow: typeof import('bootstrap-vue')['BRow']
    BToast: typeof import('bootstrap-vue')['BToast']
  }
}
